language: groovy
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
 
before_install:
 - chmod +x gradlew  

# deploy:
#   edge: true
#   provider: anynines
#   username: james.b.northrop@googlemail.com
#   password: secretpassword
#   organization: james_b_northrop_googlemail_com
#   space: test
