ifdef::env-github[]
:note-caption: :information_source:
endif::[]

= Configuration Tool
Jnorthr <james.northrop@orange.fr>
v0.1, 2017-01-25
:icons: font
:toc: left
:imagesdir: images
:sectlinks:
:sectnums:

== Status

NOTE: Travis Build Status for Master Branch: image:https://img.shields.io/travis/jnorthr/ConfigSlurper.svg[Build Status (Travis CI), link=https://travis-ci.org/jnorthr/ConfigSlurper]

A skeleton project for groovy users. Clone includes gradle 3.1 build tool wrapper and folder structure like maven/gradle for use with JDK7+ (but not JDK6)
even though the config code will run on JDK7+

Use this project jar as a configuration file maintenance tool. Reads and writes JSON-formatted text files.

== Pre-requisites

 . Working internet connection
 . Installed Git client to copy/clone this repo
 . Ability to use terminal console

== Steps

 . open terminal console

 . change directory ( cd ) into target folder location

 . run this command to create a folder named ConfigSlurper and copy down all the pieces :

	*git clone https://github.com/jnorthr/ConfigSlurper.git*

 . *cd ConfigSlurper*

 . *./gradlew*

 . defaultTasks are declared and these tasks run automatically, when you use gradlew with no parameters 

''''

